/*==============================================================
  Heavy Machinery Sales Analysis
  File: 04_03_Customer_Analysis.sql
  Section: Customer Value, Concentration, and Segmentation
==============================================================

Purpose:
Analyze customer spending, revenue concentration, customer value,
and the characteristics of the highest-revenue customers.

Analysis Scope:
- Q3: Top 10 customers by total spending
- Q3.1: Revenue contribution of top customers
- Q3.2: Pareto analysis of customer revenue
- Q3.3: Average revenue per customer
- Q3.4: Median revenue per customer
- Q4: Profile of the top 10 highest-spending customers
- Q4.1: Customer revenue analysis by industry

Execution Order:
Run this script after completing:
- 02_Data_Profiling.sql
- 03_Data_Cleaning.sql
- 04_01_Dataset_Exploration.sql
- 04_02_Time_Analysis.sql

Important:
- Customer value is measured using revenue recorded in HMSales.
- Only customers represented in HMSales are included in spending
  and revenue-concentration analyses unless otherwise stated.
- This script is read-only and does not modify source data.
==============================================================*/

set nocount on;

/*==============================================================
  Q3. Top 10 Customers by Total Spending
  --------------------------------------------------------------
  Business Question:
  Which 10 customers generated the highest total revenue?

  Objective:
  Rank customers by total spending and compare their order
  activity and total quantity purchased.
==============================================================*/

-- Calculate revenue and purchasing activity for each customer.
;with CustomerPerformance as
(
    select
        s.CustomerKey,
        count(distinct s.Invoice) as TotalOrders,
        sum(cast(s.Qty as bigint)) as TotalQuantityPurchased,
        sum(cast(s.Revenue as bigint)) as TotalSpending
    from dbo.HMSales as s
    group by
        s.CustomerKey
),

-- Rank customers by spending while preserving equal rankings.
CustomerSpendingRanking as
(
    select
        CustomerKey,
        TotalOrders,
        TotalQuantityPurchased,
        TotalSpending,
        dense_rank() over
        (
            order by TotalSpending desc
        ) as CustomerSpendingRank
    from CustomerPerformance
)

-- Return customers within the 10 highest spending ranks.
select
    csr.CustomerSpendingRank,
    csr.CustomerKey,
    c.CustomerName,
    csr.TotalOrders,
    csr.TotalQuantityPurchased,
    cast(
        csr.TotalSpending / 1000000.0
        as decimal(12, 2)
    ) as TotalSpending_Million
from CustomerSpendingRanking as csr
inner join dbo.HMCustomers as c
    on csr.CustomerKey = c.CustomerKey
where csr.CustomerSpendingRank <= 10
order by
    csr.CustomerSpendingRank,
    csr.CustomerKey;
/*==============================================================
  Q3 Business Insight
  --------------------------------------------------------------
  Walmart ranked first with 7.13 million in total spending,
  followed by Cargill at 7.10 million and Nestle at 7.07 million.

  Spending among the top 10 customers was relatively close,
  ranging from 6.74 million to 7.13 million. The difference
  between the first- and tenth-ranked customers was only
  0.39 million.

  Walmart also recorded the highest number of orders among the
  top 10 customers, with 844 distinct invoices and 888 units
  purchased.

  Nestle ranked third in total spending despite having the
  lowest order count among the top 10 customers, with 767
  distinct invoices. This suggests a comparatively higher
  average revenue per order and should be examined further.

  No customers shared the same spending rank based on their
  unrounded total revenue, so the top 10 spending ranks produced
  exactly 10 customers in this result.
==============================================================*/

/*==============================================================
  Q3.1 Revenue Contribution of Top Customers
  --------------------------------------------------------------
  Business Question:
  What percentage of total company revenue is generated by each
  of the top 10 highest-spending customer ranks?

  Objective:
  Measure the individual revenue contribution of each top
  customer relative to total revenue across all customers.
==============================================================*/

-- Calculate total revenue generated by each customer.
;with CustomerRevenue as
(
    select
        s.CustomerKey,
        sum(cast(s.Revenue as bigint)) as TotalRevenue
    from dbo.HMSales as s
    group by
        s.CustomerKey
),

-- Rank customers and calculate their individual contribution.
CustomerRevenueContribution as
(
    select
        CustomerKey,
        TotalRevenue,
        dense_rank() over
        (
            order by TotalRevenue desc
        ) as CustomerSpendingRank,
        TotalRevenue * 100.0
        / nullif(sum(TotalRevenue) over (), 0)
            as RevenueContributionPercent
    from CustomerRevenue
)

-- Return customers within the 10 highest spending ranks.
select
    crc.CustomerSpendingRank,
    crc.CustomerKey,
    c.CustomerName,
    cast(
        crc.TotalRevenue / 1000000.0
        as decimal(12, 2)
    ) as TotalSpending_Million,
    cast(
        crc.RevenueContributionPercent
        as decimal(8, 4)
    ) as RevenueContributionPercent
from CustomerRevenueContribution as crc
inner join dbo.HMCustomers as c
    on crc.CustomerKey = c.CustomerKey
where crc.CustomerSpendingRank <= 10
order by
    crc.CustomerSpendingRank,
    crc.CustomerKey;

/*==============================================================
  Q3.1 Business Insight
  --------------------------------------------------------------
  Walmart had the largest individual revenue contribution among
  all customers, accounting for approximately 0.1098% of total
  company revenue.

  Individual contributions among the top 10 customers were very
  similar, ranging from approximately 0.1037% to 0.1098%.

  Together, the top 10 customers generated approximately 1.06%
  of total company revenue. Therefore, the company does not appear
  to be highly dependent on any single top customer or on this
  small group of highest-spending customers.

  However, this result alone does not describe revenue
  concentration across the broader customer base. The cumulative
  Pareto analysis in Q3.2 will determine how many customers are
  required to generate 80% of total revenue.
==============================================================*/

/*==============================================================
  Q3.2 Customer Pareto Analysis
  --------------------------------------------------------------
  Business Question:
  What percentage of purchasing customers is required to
  generate at least 80% of total revenue?

  Objective:
  Measure customer revenue concentration and evaluate whether
  the dataset follows the traditional 80/20 Pareto pattern.
==============================================================*/

-- Calculate total revenue generated by each purchasing customer.
;with CustomerRevenue as
(
    select
        s.CustomerKey,
        sum(cast(s.Revenue as bigint)) as TotalRevenue
    from dbo.HMSales as s
    group by
        s.CustomerKey
),

-- Sort customers by revenue and calculate cumulative revenue.
CustomerPareto as
(
    select
        CustomerKey,
        TotalRevenue,
        row_number() over
        (
            order by
                TotalRevenue desc,
                CustomerKey
        ) as CustomerSequence,
        sum(TotalRevenue) over
        (
            order by
                TotalRevenue desc,
                CustomerKey
            rows between unbounded preceding and current row
        ) as CumulativeRevenue,
        sum(TotalRevenue) over
        (
            order by
                TotalRevenue desc,
                CustomerKey
            rows between unbounded preceding and current row
        ) * 100.0
        / nullif(sum(TotalRevenue) over (), 0)
            as CumulativeRevenuePercent
    from CustomerRevenue
),

-- Count only customers represented in HMSales.
PurchasingCustomerCount as
(
    select
        count_big(*) as TotalPurchasingCustomers
    from CustomerRevenue
)

-- Return the first point at which cumulative revenue reaches 80%.
select top (1)
    cp.CustomerSequence as CustomersRequired,
    pcc.TotalPurchasingCustomers,
    cast(
        cp.CustomerSequence * 100.0
        / nullif(pcc.TotalPurchasingCustomers, 0)
        as decimal(8, 2)
    ) as CustomerSharePercent,
    cast(
        cp.CumulativeRevenue / 1000000.0
        as decimal(14, 2)
    ) as CumulativeRevenue_Million,
    cast(
        cp.CumulativeRevenuePercent
        as decimal(8, 2)
    ) as CumulativeRevenuePercent
from CustomerPareto as cp
cross join PurchasingCustomerCount as pcc
where cp.CumulativeRevenuePercent >= 80
order by
    cp.CustomerSequence;

/*==============================================================
  Q3.2 Business Insight
  --------------------------------------------------------------
  The Pareto analysis shows that 1,393 of the 3,939 purchasing
  customers are required to generate approximately 80% of total
  revenue.

  These customers represent 35.36% of the purchasing customer
  base and collectively generated 5,198.88 million, or 80.02%
  of total revenue.

  The dataset does not follow the traditional 80/20 pattern,
  because substantially more than 20% of customers are needed
  to generate 80% of revenue.

  This indicates moderate customer concentration rather than
  extreme dependence on a very small customer group. The result
  is also consistent with Q3.1, where the top 10 customers
  collectively contributed only approximately 1.06% of revenue.

  The remaining 64.64% of purchasing customers collectively
  generated approximately 19.98% of total revenue.
==============================================================*/

/*==============================================================
  Q3.3 Average Revenue per Customer
  --------------------------------------------------------------
  Business Question:
  What is the average total revenue generated by each
  purchasing customer?

  Objective:
  Establish an average customer-value benchmark based on
  customers represented in HMSales.
==============================================================*/

-- Calculate total revenue generated by each purchasing customer.
;with CustomerRevenue as
(
    select
        s.CustomerKey,
        sum(cast(s.Revenue as bigint)) as TotalRevenue
    from dbo.HMSales as s
    group by
        s.CustomerKey
)
select
    count_big(*) as TotalPurchasingCustomers,
    cast(
        sum(TotalRevenue) / 1000000.0
        as decimal(14, 2)
    ) as TotalRevenue_Million,
    cast(
        avg(cast(TotalRevenue as decimal(19, 2))) / 1000000.0
        as decimal(12, 2)
    ) as AverageRevenuePerCustomer_Million
from CustomerRevenue;

/*==============================================================
  Q3.3 Business Insight
  --------------------------------------------------------------
  The 3,939 purchasing customers generated approximately
  6,496.73 million in total revenue.

  Average revenue per purchasing customer was approximately
  1.65 million.

  This average provides a useful overall benchmark for comparing
  customer segments, industries, countries, or future customer
  performance.

  However, the average may be influenced by customers with
  exceptionally high spending. It should not yet be interpreted
  as the revenue generated by a typical customer.

  Q3.4 compares this average with the median customer revenue
  to evaluate the shape of the customer-spending distribution.

  The 589 customers without sales were excluded because they
  generated no recorded revenue in HMSales.
==============================================================*/

/*==============================================================
  Q3.4 Median Revenue per Customer
  --------------------------------------------------------------
  Business Question:
  What is the median revenue generated by a purchasing customer,
  and how does it compare with the average?

  Objective:
  Measure typical customer value using a statistic that is less
  affected by exceptionally high-spending customers.
==============================================================*/

-- Calculate total revenue generated by each purchasing customer.
;with CustomerRevenue as
(
    select
        s.CustomerKey,
        sum(cast(s.Revenue as bigint)) as TotalRevenue
    from dbo.HMSales as s
    group by
        s.CustomerKey
),

-- Calculate average and median customer revenue.
CustomerRevenueStatistics as
(
    select
        avg(cast(TotalRevenue as decimal(19, 2))) over ()
            as AverageRevenue,
        percentile_cont(0.5) within group
        (
            order by TotalRevenue
        ) over () as MedianRevenue
    from CustomerRevenue
)

-- Return one row containing the customer-value statistics.
select distinct
    cast(
        AverageRevenue / 1000000.0
        as decimal(12, 2)
    ) as AverageRevenuePerCustomer_Million,
    cast(
        MedianRevenue / 1000000.0
        as decimal(12, 2)
    ) as MedianRevenuePerCustomer_Million,
    cast(
        AverageRevenue / nullif(MedianRevenue, 0)
        as decimal(8, 2)
    ) as AverageToMedianRatio
from CustomerRevenueStatistics;

/*==============================================================
  Q3.4 Business Insight
  --------------------------------------------------------------
  Median revenue per purchasing customer was approximately
  0.87 million, compared with an average of 1.65 million.

  The average was approximately 1.89 times the median, meaning
  it was about 89% higher than the midpoint of the customer
  revenue distribution.

  This substantial difference indicates a positively skewed
  customer-revenue distribution. A group of higher-spending
  customers increases the average above the value generated
  by the typical purchasing customer.

  Therefore, the median of 0.87 million provides a more
  representative measure of typical customer value, while the
  average of 1.65 million remains useful for financial planning
  and aggregate revenue comparisons.

  This result supports the Pareto finding in Q3.2 that revenue
  is moderately concentrated among higher-value customers,
  although it is not dependent on only a very small group.
==============================================================*/

/*==============================================================
  Q4. Profile of the Top 10 Highest-Spending Customers
  --------------------------------------------------------------
  Business Question:
  What are the geographic, industry, and payment characteristics
  of the top 10 highest-spending customer ranks?

  Objective:
  Profile the highest-value customers to support segmentation,
  relationship management, and targeted business strategies.
==============================================================*/

-- Calculate total revenue generated by each customer.
;with CustomerRevenue as
(
    select
        s.CustomerKey,
        sum(cast(s.Revenue as bigint)) as TotalRevenue
    from dbo.HMSales as s
    group by
        s.CustomerKey
),

-- Rank customers and calculate individual revenue contribution.
CustomerProfileRanking as
(
    select
        CustomerKey,
        TotalRevenue,
        dense_rank() over
        (
            order by TotalRevenue desc
        ) as CustomerSpendingRank,
        TotalRevenue * 100.0
        / nullif(sum(TotalRevenue) over (), 0)
            as RevenueContributionPercent
    from CustomerRevenue
)

-- Return geographic and business characteristics of top customers.
select
    cpr.CustomerSpendingRank,
    cpr.CustomerKey,
    c.CustomerName,
    c.Country,
    c.Continent,
    c.Industry,
    c.Payment,
    c.ContactPerson,
    cast(
        cpr.TotalRevenue / 1000000.0
        as decimal(12, 2)
    ) as TotalSpending_Million,
    cast(
        cpr.RevenueContributionPercent
        as decimal(8, 4)
    ) as RevenueContributionPercent
from CustomerProfileRanking as cpr
inner join dbo.HMCustomers as c
    on cpr.CustomerKey = c.CustomerKey
where cpr.CustomerSpendingRank <= 10
order by
    cpr.CustomerSpendingRank,
    cpr.CustomerKey;

/*==============================================================
  Q4 Business Insight
  --------------------------------------------------------------
  The top 10 highest-spending customers were distributed across
  seven countries and four continents, indicating geographic
  diversity among the company's highest-value accounts.

  Europe contained five of the top 10 customers, followed by
  America and Africa with two customers each and Oceania with
  one customer.

  The Netherlands had the strongest country representation,
  with Shell, Royal BAM, and Phillips66 accounting for three
  of the top 10 customer positions.

  Oil & Gas was the most frequently represented industry, with
  three customers: Shell, Phillips66, and Statoil. Retail and
  Food Processing each contributed two customers, while Mining,
  Construction, and Conglomerate each contributed one.

  Payment methods were evenly distributed between CashAdvance
  and COD, with four customers each. The remaining two customers
  used EFT.

  Although European and Oil & Gas customers were strongly
  represented in the top 10, each individual customer contributed
  only approximately 0.10% to 0.11% of total revenue. Therefore,
  geographic or industry representation in this small group
  should not be interpreted as overall company-level revenue
  concentration.
==============================================================*/

/*==============================================================
  Q4.1 Customer Revenue Analysis by Industry
  --------------------------------------------------------------
  Business Question:
  Which customer industries generate the highest total revenue,
  and how does customer value differ across industries?

  Objective:
  Compare industries by customer count, total revenue, revenue
  contribution, and average revenue per purchasing customer.
==============================================================*/

-- Aggregate customer and revenue metrics by industry.
;with IndustryRevenue as
(
    select
        c.Industry,
        count(distinct s.CustomerKey) as ActiveCustomers,
        sum(cast(s.Revenue as bigint)) as TotalRevenue
    from dbo.HMSales as s
    inner join dbo.HMCustomers as c
        on s.CustomerKey = c.CustomerKey
    group by
        c.Industry
),

-- Rank industries and calculate customer and revenue shares.
IndustryPerformance as
(
    select
        Industry,
        ActiveCustomers,
        TotalRevenue,
        dense_rank() over
        (
            order by TotalRevenue desc
        ) as IndustryRevenueRank,
        ActiveCustomers * 100.0
        / nullif(sum(ActiveCustomers) over (), 0)
            as ActiveCustomerSharePercent,
        TotalRevenue * 100.0
        / nullif(sum(TotalRevenue) over (), 0)
            as RevenueContributionPercent,
        TotalRevenue * 1.0
        / nullif(ActiveCustomers, 0)
            as AverageRevenuePerCustomer
    from IndustryRevenue
)

-- Return industry-level customer and revenue performance.
select
    IndustryRevenueRank,
    Industry,
    ActiveCustomers,
    cast(
        ActiveCustomerSharePercent
        as decimal(8, 2)
    ) as ActiveCustomerSharePercent,
    cast(
        TotalRevenue / 1000000.0
        as decimal(14, 2)
    ) as TotalRevenue_Million,
    cast(
        RevenueContributionPercent
        as decimal(8, 2)
    ) as RevenueContributionPercent,
    cast(
        AverageRevenuePerCustomer / 1000000.0
        as decimal(12, 2)
    ) as AverageRevenuePerCustomer_Million
from IndustryPerformance
order by
    IndustryRevenueRank,
    Industry;


/*==============================================================
  Q4.1 Business Insight
  --------------------------------------------------------------
  Reseller was the dominant customer industry, containing
  3,572 purchasing customers, or 90.68% of the active customer
  base.

  The Reseller segment generated 4,541.45 million and contributed
  69.90% of total revenue. However, its average revenue per
  customer was only 1.27 million, substantially below the
  company-wide average of 1.65 million.

  Reseller revenue is therefore driven primarily by its large
  customer population rather than high individual customer value.

  Construction Contractors ranked second, generating 787.23
  million, or 12.12% of total revenue, from 157 customers.
  Realtors ranked third with 331.80 million, or 5.11%, from
  63 customers.

  Together, the top three industries generated 87.13% of total
  revenue, indicating strong revenue concentration by industry
  despite relatively low concentration among individual top
  customers.

  Oil & Gas represented only 0.63% of purchasing customers but
  contributed 2.44% of revenue, with an average of 6.34 million
  per customer. This explains its strong representation among
  the top 10 individual customers in Q4.

  Food Processing recorded the highest average revenue per
  customer at 7.09 million. However, this result was based on
  only two customers and should not be generalized without
  additional observations.

  Industries with very small customer counts may show high
  average customer value, but these averages are less stable
  and more sensitive to individual customer performance.
==============================================================*/

/*==============================================================
  Customer Analysis Summary
  --------------------------------------------------------------
  - Walmart ranked as the highest-spending customer, generating
    approximately 7.13 million in total revenue.

  - The top 10 customers collectively contributed only about
    1.06% of total revenue, indicating low dependence on any
    single high-value customer.

  - The Pareto analysis showed that 1,393 of 3,939 purchasing
    customers, or 35.36%, generated approximately 80.02% of
    total revenue.

  - Customer revenue does not follow the traditional 80/20 rule.
    Revenue is distributed across a broader customer group than
    the classic Pareto pattern would suggest.

  - Purchasing customers generated 6,496.73 million in total
    revenue, with an average of 1.65 million per customer.

  - Median revenue per customer was 0.87 million. The average
    was 1.89 times the median, indicating a positively skewed
    customer-revenue distribution.

  - The top 10 customers were distributed across seven countries
    and four continents. Europe contained five of these customers.

  - Oil & Gas was the most frequently represented industry among
    the top 10 individual customers.

  - Reseller was the dominant industry across the full customer
    base, representing 90.68% of purchasing customers and
    generating 69.90% of total revenue.
	
  - The top three industries (Reseller, Construction Contractor,
    and Realtor) generated 87.13% of total company revenue.

  - Food Processing recorded the highest average revenue per
    customer at 7.09 million, but the result was based on only
    two customers.
==============================================================*/


/*==============================================================
  Business Recommendations
  --------------------------------------------------------------
  1. Develop a tiered customer-retention strategy for the 1,393
     customers that collectively generate approximately 80% of
     total revenue.

  2. Maintain personalized relationship management for the
     highest-spending customers, while recognizing that no single
     customer represents a significant share of company revenue.

  3. Monitor and reduce industry-concentration risk by developing
     additional customer segments while maintaining the Reseller
     relationships that generate 69.90% of total revenue.

  4. Increase average customer value within the Reseller segment
     through customer tiers, cross-selling, upselling, and
     product-bundle strategies.

  5. Evaluate customer-development opportunities in Construction
     Contractor, Realtor, and Oil & Gas segments, which show
     stronger average customer value than the Reseller segment.

  6. Investigate industries with high average customer revenue
     but small customer populations, such as Food Processing.
     Use controlled acquisition tests before making large
     investments in these segments.

  7. Use median customer revenue as the primary benchmark for
     typical customer value, while retaining average revenue for
     financial planning and aggregate comparisons.

  8. Evaluate customer and industry performance using profit,
     retention, purchase frequency, and recent activity in
     addition to revenue before making resource-allocation
     decisions.
==============================================================*/


/*==============================================================
  End of 04_03_Customer_Analysis.sql
==============================================================*/

set nocount off;



